package gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Lasiru
 */
public class Loading extends javax.swing.JFrame {

    int x;
    Timer timer;

    public Loading() {
        initComponents();
        pbr.setBackground(getBackground());
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());

        ActionListener actl = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                x++;
                if (x <= 100) {
                    pbr.setValue(x);
                    loading_value.setText(x + "% ");

                    if (x == 15) {
                        loading_lbl.setText("Turning On Modules...");
                    }
                    if (x == 30) {
                        loading_lbl.setText("Loading Modules...");
                    }
                    if (x == 50) {
                        loading_lbl.setText("Connecting to Database...");
                    }
                    if (x == 70) {
                        loading_lbl.setText("Connection Successful...");
                    }
                    if (x == 85) {
                        loading_lbl.setText("Launching Application...");
                    }

                } else {
                    timer.stop();

                    Login login = new Login();
                    login.setVisible(true);
                    dispose();
                }
            }
        };
        timer = new Timer(100, actl);
        timer.setRepeats(true);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        img_keyboard = new javax.swing.JLabel();
        pbr = new javax.swing.JProgressBar();
        img_books = new javax.swing.JLabel();
        loading_lbl = new javax.swing.JLabel();
        loading_value = new javax.swing.JLabel();
        bg_color = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Management System");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("SCHOOL MANAGEMENT SYSTEM");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        img_keyboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/content.png"))); // NOI18N
        jPanel1.add(img_keyboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 260, 250));

        pbr.setBackground(java.awt.Color.lightGray);
        pbr.setForeground(java.awt.Color.darkGray);
        pbr.setBorderPainted(false);
        pbr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(pbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 800, 20));

        img_books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/books.png"))); // NOI18N
        jPanel1.add(img_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 140));

        loading_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loading_lbl.setForeground(new java.awt.Color(255, 255, 255));
        loading_lbl.setText("Loading...");
        jPanel1.add(loading_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        loading_value.setForeground(new java.awt.Color(255, 255, 255));
        loading_value.setText("0 %");
        jPanel1.add(loading_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 40, 20));

        bg_color.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bg_color.setForeground(new java.awt.Color(255, 255, 255));
        bg_color.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.jpg"))); // NOI18N
        jPanel1.add(bg_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_color;
    private javax.swing.JLabel img_books;
    private javax.swing.JLabel img_keyboard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loading_lbl;
    private javax.swing.JLabel loading_value;
    private javax.swing.JLabel name;
    private javax.swing.JProgressBar pbr;
    // End of variables declaration//GEN-END:variables
}
