package gui;

import db.DatabaseConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author Lasiru
 */
public class StudentSearch extends javax.swing.JFrame {

    Connection connection = null;
    Statement stmt = null;
    ResultSet rs = null;

    public StudentSearch() {
        initComponents();

        connection = DatabaseConnection.getconnection();
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        std_name = new javax.swing.JTextField();
        std_age = new javax.swing.JTextField();
        std_dob = new javax.swing.JTextField();
        std_id = new javax.swing.JTextField();
        std_address = new javax.swing.JTextField();
        std_guardian = new javax.swing.JTextField();
        std_contact = new javax.swing.JTextField();
        std_admission = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        std_class = new javax.swing.JComboBox<>();
        std_gender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student");
        setBackground(java.awt.Color.darkGray);
        setUndecorated(true);
        setSize(new java.awt.Dimension(384, 545));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setMinimumSize(new java.awt.Dimension(330, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(291, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(java.awt.Color.lightGray);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel11.setText("Search Student");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 170, 49));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout (1).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 40));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Admission No.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 40));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Age");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 40));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Date of Birth");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 40));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Guardian");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 40));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Contact No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 40));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 40));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 40));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Admission Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 120, 40));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Class");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 100, 40));

        std_name.setEditable(false);
        std_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 220, 30));

        std_age.setEditable(false);
        std_age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 220, 30));

        std_dob.setEditable(false);
        std_dob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 220, 30));

        std_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        std_id.setText("enter student id.");
        std_id.setToolTipText("");
        std_id.setName(""); // NOI18N
        std_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                std_idMouseClicked(evt);
            }
        });
        jPanel1.add(std_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 220, 30));

        std_address.setEditable(false);
        std_address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 220, 30));

        std_guardian.setEditable(false);
        std_guardian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_guardian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 220, 30));

        std_contact.setEditable(false);
        std_contact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 220, 30));

        std_admission.setEditable(false);
        std_admission.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_admission, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 220, 30));

        btn_clear.setBackground(java.awt.Color.lightGray);
        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        btn_search.setBackground(java.awt.Color.lightGray);
        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_search.setText("Search");
        btn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        std_class.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        std_class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12", "Grade 13" }));
        std_class.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        std_class.setEnabled(false);
        jPanel1.add(std_class, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 90, 30));

        std_gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        std_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        std_gender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        std_gender.setEnabled(false);
        std_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_genderActionPerformed(evt);
            }
        });
        jPanel1.add(std_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void std_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_genderActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        try {

            stmt = connection.createStatement();
            int sId = 0;
            try {
                sId = Integer.parseInt(std_id.getText());
            } catch (NumberFormatException a) {
                JOptionPane.showMessageDialog(rootPane, "Invalid admission number!");
            }
            String query = "SELECT * FROM student";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                if (sId == rs.getInt("Student_Id")) {
                    std_name.setText(rs.getString("Name"));
                    std_dob.setText(String.format("%s", rs.getDate("Date_of_Birth")));
                    std_age.setText(String.format("%s", rs.getInt("Age")));
                    std_gender.setSelectedItem(rs.getString("Gender"));
                    std_address.setText(rs.getString("Address"));
                    std_guardian.setText(rs.getString("Guardian"));
                    std_contact.setText(String.format(0 + "%s", rs.getInt("Contact_No")));
                    std_class.setSelectedItem(rs.getString("Class"));
                    std_admission.setText(String.format("%s", rs.getDate("Admission_Date")));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        std_id.setText("");
        std_name.setText("");
        std_dob.setText("");
        std_age.setText("");
        std_gender.setSelectedItem("Male");
        std_address.setText("");
        std_guardian.setText("");
        std_contact.setText("");
        std_class.setSelectedItem(" ");
        std_admission.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void std_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_std_idMouseClicked
        std_id.setText("");
    }//GEN-LAST:event_std_idMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField std_address;
    private javax.swing.JTextField std_admission;
    private javax.swing.JTextField std_age;
    private javax.swing.JComboBox<String> std_class;
    private javax.swing.JTextField std_contact;
    private javax.swing.JTextField std_dob;
    private javax.swing.JComboBox<String> std_gender;
    private javax.swing.JTextField std_guardian;
    private javax.swing.JTextField std_id;
    private javax.swing.JTextField std_name;
    // End of variables declaration//GEN-END:variables
}
