package gui;

import db.DatabaseConnection;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lasiru
 */
public class StudentAdd extends javax.swing.JFrame {

    public StudentAdd() {
        initComponents();
        //lbl_error.setVisible(false);
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        std_name = new javax.swing.JTextField();
        std_age = new javax.swing.JTextField();
        std_dob = new javax.swing.JTextField();
        std_id = new javax.swing.JTextField();
        std_address = new javax.swing.JTextField();
        std_guardian = new javax.swing.JTextField();
        std_contact = new javax.swing.JTextField();
        std_admission = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        std_class = new javax.swing.JComboBox<>();
        std_gender = new javax.swing.JComboBox<>();
        lbl_error1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student");
        setBackground(java.awt.Color.darkGray);
        setUndecorated(true);
        setSize(new java.awt.Dimension(384, 545));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setMinimumSize(new java.awt.Dimension(330, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(291, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(java.awt.Color.lightGray);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel11.setText("New Student");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 150, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout (1).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 40));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Admission No.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 40));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Age");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 40));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Date of Birth");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 40));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Guardian");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 40));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Contact No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 40));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 40));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 40));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Admission Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 120, 40));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Class");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 100, 40));

        std_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 220, 30));

        std_age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 220, 30));

        std_dob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        std_dob.setText("ex:-  year/month/date");
        std_dob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                std_dobMouseClicked(evt);
            }
        });
        jPanel1.add(std_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 220, 30));

        std_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        std_id.setToolTipText("");
        std_id.setName(""); // NOI18N
        std_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_idActionPerformed(evt);
            }
        });
        jPanel1.add(std_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 220, 30));

        std_address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 220, 30));

        std_guardian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_guardian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 220, 30));

        std_contact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(std_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 220, 30));

        std_admission.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        std_admission.setText("ex:-  year/month/date");
        std_admission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                std_admissionMouseClicked(evt);
            }
        });
        jPanel1.add(std_admission, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 220, 30));

        btn_clear.setBackground(java.awt.Color.lightGray);
        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 50, 70, -1));

        btn_submit.setBackground(java.awt.Color.lightGray);
        btn_submit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 100, 40));

        std_class.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        std_class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12", "Grade 13" }));
        std_class.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(std_class, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 90, 30));

        std_gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        std_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        std_gender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        std_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_genderActionPerformed(evt);
            }
        });
        jPanel1.add(std_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 100, 30));

        lbl_error1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_error1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void std_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_genderActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        try {
            int sId = 0;
            try {
                sId = Integer.parseInt(std_id.getText());
            } catch (NumberFormatException a) {
                JOptionPane.showMessageDialog(rootPane, "Invalid admission number!");
            }
            String sName = std_name.getText();
            long Dob = Date.parse(std_dob.getText());
            java.sql.Date sDob = new java.sql.Date(Dob);
            int sAge = Integer.parseInt(std_age.getText());
            String sGender = (String) std_gender.getSelectedItem();
            String sAddress = std_address.getText();
            String sGuardian = std_guardian.getText();
            int sContact = Integer.parseInt(std_contact.getText());
            String sGrade = (String) std_class.getSelectedItem();
            long Admission = Date.parse(std_admission.getText());
            java.sql.Date sAdmission = new java.sql.Date(Admission);

            if (!sDob.equals("") && (!std_age.getText().equals("")) && (std_age.getText() != null) && (!std_contact.getText().equals("")) && (std_contact.getText() != null) && (!sAdmission.equals(""))) {

                DatabaseConnection.getconnection().createStatement().executeUpdate("insert into student (Student_Id,Name,Date_of_Birth,Age,Gender,Address,Guardian,Contact_No,Class,Admission_Date) values ('" + sId + "','" + sName + "','" + sDob + "','" + sAge + "','" + sGender + "','" + sAddress + "','" + sGuardian + "','" + sContact + "','" + sGrade + "','" + sAdmission + "')");
                JOptionPane.showMessageDialog(rootPane, "Student Saved Successfuly");
                lbl_error1.setText("");
            }
        } catch (Exception e) {
            // e.printStackTrace();
            lbl_error1.setVisible(true);
            lbl_error1.setText("Fields cannot be empty.");

        }

    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        std_id.setText("");
        std_name.setText("");
        std_dob.setText("");
        std_age.setText("");
        std_gender.setSelectedItem("Male");
        std_address.setText("");
        std_guardian.setText("");
        std_contact.setText("");
        std_class.setSelectedItem(" ");
        std_admission.setText("");
        lbl_error1.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void std_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_idActionPerformed

    private void std_dobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_std_dobMouseClicked
        std_dob.setText("");
    }//GEN-LAST:event_std_dobMouseClicked

    private void std_admissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_std_admissionMouseClicked
        std_admission.setText("");
    }//GEN-LAST:event_std_admissionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_error1;
    private javax.swing.JTextField std_address;
    private javax.swing.JTextField std_admission;
    private javax.swing.JTextField std_age;
    private javax.swing.JComboBox<String> std_class;
    private javax.swing.JTextField std_contact;
    private javax.swing.JTextField std_dob;
    private javax.swing.JComboBox<String> std_gender;
    private javax.swing.JTextField std_guardian;
    private javax.swing.JTextField std_id;
    private javax.swing.JTextField std_name;
    // End of variables declaration//GEN-END:variables
}
